name: Issue and PR Automation
on:
  workflow_call:
    inputs:
      project_owner:
        required: true
        description: The ID for the user who owns the project
        type: string
      project_id:
        required: true
        description: The numeric ID of the Github project
        type: number
    secrets:
      personal_access_token:
        required: true
        description: An access token with `project` permission

jobs:
  add-to-project:
    name: Issue and PR Automation
    runs-on: ubuntu-latest
    steps:
      - name: Add to project
        uses: actions/add-to-project@v2
        with:
          project-url: https://github.com/users/${{ inputs.project_owner }}/projects/${{ inputs.project_id }}
          github-token: ${{ secrets.personal_access_token }}
